name: main - aarch64

on:
  workflow_dispatch:
  
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: Build and Push image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Get the version
        run: |
          echo ::set-env name=TAG_NAME::$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: |
            [
              {
                "id": "qiot-central",
                "username": "${env.ARTIFACTORY_USERNAME_REF}",
                "password": "${env.ARTIFACTORY_TOKEN_REF}"
              },
              {
                "id": "qiot-snapshots",
                "username": "${env.ARTIFACTORY_USERNAME_REF}",
                "password": "${env.ARTIFACTORY_TOKEN_REF}"
              }
            ]

      - name: Build the Docker image
        run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker build -t quay.io/qiotmanufacturing/edge-machinery:${{ env.TAG_NAME }}-aarch64 -f src/main/docker/Dockerfile.native.multiarch .

      - name: Push To Quay
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/qiotmanufacturing 
          image: edge-machinery
          tag: ${{ env.TAG_NAME }}-aarch64
          username: ${{ secrets.QUAY_MANUFACTURING_USERNAME }}
          password: ${{ secrets.QUAY_MANUFACTURING_PASSWORD }}
